<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Sanjeet3149591" name="com.CBSCorporate.testcase.CreatePayeeTestCases" tests="3" failures="0" timestamp="28 Jan 2019 21:56:20 GMT" time="0.627" errors="1">
  <testcase name="loginPage" time="0.000" classname="com.CBSCorporate.testcase.CreatePayeeTestCases">
    <skipped/>
  </testcase> <!-- loginPage -->
  <testcase name="GlobalInitialization" time="0.627" classname="com.CBSCorporate.testcase.CreatePayeeTestCases">
    <error type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
at com.CBSCorporate.testcase.CreatePayeeTestCases.GlobalInitialization(CreatePayeeTestCases.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:104)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:71)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:45)
at com.CBSCorporate.utility.selenium.SeleniumUtils.<init>(SeleniumUtils.java:21)
at com.CBSCorporate.utility.selenium.AlertBox.<init>(AlertBox.java:18)
at com.CBSCorporate.utility.selenium.SeleniumFramework.<clinit>(SeleniumFramework.java:15)
... 26 more
]]>
    </error>
  </testcase> <!-- GlobalInitialization -->
  <testcase name="createpayee" time="0.000" classname="com.CBSCorporate.testcase.CreatePayeeTestCases">
    <skipped/>
  </testcase> <!-- createpayee -->
</testsuite> <!-- com.CBSCorporate.testcase.CreatePayeeTestCases -->
